### ISSUE TITLE
beta channel

### ISSUE THREAD

**Issue by nedrichards** [flathub/org.gnome.gitlab.somas.Apostrophe#1]
will there be a beta channel for this? if so we need it created before we push the migration hint and archive the old repo.

**Comment by bilelmoussaoui** [comment]
I have been talking to the app developer and they are planning to push an update to the old app-id with a message telling the users to use Apostrophe instead of Uberwriter before eol the old repo

**Comment by nedrichards** [comment]
You mean like https://github.com/flathub/de.wolfvollprecht.UberWriter/pull/12 ;-) Yes, we need to make sure that everything that already exists redirects appropriately (I say this as an existing and keen uberwriter user!)

**Comment by bilelmoussaoui** [comment]
> You mean like [flathub/de.wolfvollprecht.UberWriter#12](https://github.com/flathub/de.wolfvollprecht.UberWriter/pull/12) ;-) Yes, we need to make sure that everything that already exists redirects appropriately (I say this as an existing and keen uberwriter user!)

That only works if you update your applications using flatpak CLI. It's not supported by any frontend as far as I know yet

**Comment by somas95** [comment]
For the moment I'll keep this as it is. I'll push an update for both the regular and the beta channel on uberwriter (a rebase of 2.1.5 with a message pointing to Apostrophe)
