### ISSUE TITLE
org.gnome.Platform//41 is end-of-life

### ISSUE THREAD

**Issue by rusty-snake** [flathub/org.gnome.gitlab.somas.Apostrophe#10]
The GNOME 41 runtime is no longer supported as of September 17, 2022. Please ask your application developer to migrate to a supported platform.

**Comment by Jacalz** [comment]
It seems to me like this is using version 42 now (https://github.com/flathub/org.gnome.gitlab.somas.Apostrophe/blob/7d136cb146033f7b49ee7b1d915e0dc0ad95885d/org.gnome.gitlab.somas.Apostrophe.json#L4). Can this be closed?
