### ISSUE TITLE
Dark mode not enabled when selecting dark mode 

### ISSUE THREAD

**Issue by sohrob** [flathub/org.gnome.gitlab.somas.Apostrophe#2]
I've installed Apostrophe on Debian 10 (Buster) via Flatpak and when I select dark mode it still stays white. 

Machine specs:

Nvidia driver
Xfce desktop environment

**Comment by somas95** [comment]
Wich theme do you use?
________________________________

**Comment by sohrob** [comment]
I use Materia Dark Compact

**Comment by somas95** [comment]
There you have it. 3d party themes are not supported (think about css and webpages, while your browser may let you to force a custom css stylesheet to all webpages, you may expect them to break). For more info about that, see https://stopthemingmy.app/

My advice is just to use Adwaita. Also, from so on please file bug reports to the project repo at https://gitlab.gnome.org/somas/apostrophe
